version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "personalize-monitor"
s3_prefix = "personalize-monitor"
parameter_overrides = "CampaignARNs=\"all\" RecommenderARNs=\"all\" AutoCreateUtilizationAlarms=\"Yes\" UtilizationThresholdAlarmLowerBound=\"100\" AutoAdjustMinTPS=\"Yes\" AutoCreateIdleAlarms=\"Yes\" IdleThresholdHours=\"24\" AutoDeleteOrStopIdleResources=\"No\""
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []
